In [ ]:
import numpy as np

np.zeros(10)

## Creating Arrays

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 3, 5, 7, 8, 12])
a

array([ 1,  3,  5,  7,  8, 12])

In [8]:
a[2] = 99
a

array([ 1,  3, 99,  7,  8, 12])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

## Multi-Dementional Arrays

In [14]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [18]:
n[0, 1]

np.int64(2)

In [19]:
n[0, 1].item()

2